version: '3.7'
services:
  quasar:
    build: ./frontend
    ports: 
      - "8080:8080"
    networks:
      - backend

  node:
    build: ./backend
    networks:
      - backend
    # Quitar para no hacer el backend accesible por todo el mundo
    ports:
      - "3000:3000"

networks:
  backend:
    name: app_backend