name: Publish Docker image in GitHub Packages

on:
  push:
    branches: [docker]
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages

    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: docker.pkg.github.com/PaulaExposito/TFG-TrackYourTrails
          tag-sha: true
          tag-edge: false
          tag-latest: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to GH Packages
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PACKAGE_TOKEN  }}
      
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PACKAGE_TOKEN  }}
          registry: docker.pkg.github.com
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }} 

      # - name: Push to GitHub Packages
      #   uses: docker/build-push-action@v1
      #   with:
      #     # username: ${{ github.actor }}
      #     # password: ${{ secrets.GITHUB_TOKEN }}
      #     # registry: docker.pkg.github.com
      #     repository: PaulaExposito/TFG-TrackYourTrails/app_node
      #     tag_with_ref: true
      #     push: true
      #     file: ./backend/Dockerfile

      # - name: Push image
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: true
      #     tags: ${{ steps.docker_meta.outputs.tags }}
      #     file: ./Dockerfile
