name: Node.js CI

on:
  push:
    branches: [ main, api ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
      node-version: [15.x]
        #node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
    #  run: npm install
    - run: npm ci
    - run: npm run serve &
    - run: npm test:api
  