name: Node API Tests CI

on:
  push:
    branches: [ main, api ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
        #node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Go to Backend directory
        run: cd backend

      - name: Install dependencies
      #  run: npm install
        run: npm ci
      - run: npm run serve &
      - run: npm run test:api
